version: '2'

services:

  redzilla:
    image: opny/redzilla
    environment:
      NETWORK: redzilla_redzilla
      DOMAIN: redzilla.localhost
    networks:
      - redzilla
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data

networks:
  redzilla:
    driver: bridge
